### ISSUE TITLE
MacOS build does not cd

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#1006]
Looks like the macOS DMG installed doesn't pick up Chromium Embedded in the rpath:

```
/Applications/Exokit.app/Contents/MacOS/scripts/exokit-macos "https://aframe.io/a-painter"
internal/modules/cjs/loader.js:800
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Applications/Exokit.app/Contents/MacOS/build/Release/exokit.node, 1): Library not loaded: @rpath/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: /Applications/Exokit.app/Contents/MacOS/build/Release/exokit.node
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:800:18)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Applications/Exokit.app/Contents/MacOS/src/native-bindings.js:19:18
    at Object.<anonymous> (/Applications/Exokit.app/Contents/MacOS/src/native-bindings.js:26:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
```

The fix for this might be to cd into the `exokit` directory when we start the app.

**Comment by modulesio** [comment]
Fixed in https://github.com/exokitxr/exokit/pull/1012.
