### ISSUE TITLE
macOS Library not loaded rpath Chromium Embedded Framework image not found

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#1011]
macOS
```
Applications/Exokit.app/Contents/MacOS/scripts/exokit-macos "https://aframe.io/a-painter"
internal/modules/cjs/loader.js:800
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Applications/Exokit.app/Contents/MacOS/build/Release/exokit.node, 1): Library not loaded: @rpath/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: /Applications/Exokit.app/Contents/MacOS/build/Release/exokit.node
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:800:18)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Applications/Exokit.app/Contents/MacOS/src/native-bindings.js:19:18
    at Object.<anonymous> (/Applications/Exokit.app/Contents/MacOS/src/native-bindings.js:26:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
```

**Comment by chrisplatorres** [comment]
Going to reopen this issue as I thought about it and this requires a bit more testing to ensure that it is fixed.

**Comment by chrisplatorres** [comment]
Ok, tested again and confirmed working.
