### ISSUE TITLE
window.matchMedia is not a function

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#1204]
```
$ node . -x webvr https://app.showhow.nz/
(node:20668) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'
A-Frame Version: 0.9.2 (Date 2019-05-20, Commit #552ae96)
three Version (https://github.com/supermedium/three.js): ^0.102.2
WebVR Polyfill Version: ^0.10.10
ErrorEvent {
  type: 'error',
  target: <script src="/app/static/js/main.37608af7.chunk.js"></script>,
  bubbles: false,
  cancelable: false,
  defaultPrevented: false,
  propagationStopped: false,
  currentTarget: <script src="/app/static/js/main.37608af7.chunk.js"></script>,
  message: 'window.matchMedia is not a function',
  stack: '/app/static/js/main.37608af7.chunk.js:1\n' +
    '(self.webpackJsonp=self.webpackJsonp||[]).push([[1],{1:function(e,t,n){"use
 ' +
    'strict";n.d(t,"ob",function(){return r}),n.d(t,"d",function(){return ' +
    'a}),n.d(t,"jd",function(){return o}),n.d(t,"I",function(){return ' +
    's}),n.d(t,"Jd",function(){return c}),n.d(t,"lc",function(){return ' +
    'u}),n.d(t,"bf",function(){return d}),n.d(t,"kc",function(){return ' +
    'l}),n.d(t,"af",function(){return f}),n.d(t,"a",function(){return ' +
    'h}),n.d(t,"gd",function(){return b}),n.d(t,"Sc",function(){return ' +
    'p}),n.d(t,"Gf",function(){return m}),n.d(t,"gc",function(){return ' +
    'g}),n.d(t,"xf",function(){return v}),n.d(t,"Oc",function(){return ' +
    'E}),n.d(t,"Cf",function(){return O}),n.d(t,"Nc",function(){return ' +
    '_}),n.d(t,"Bf",function(){return y}),n.d(t,"Nb",function(){return ' +
    'S}),n.d(t,"Le",function(){return j}),n.d(t,"Ob",function(){return ' +
    'T}),n.d(t,"Me",function(){return I}),n.d(t,"Pb",function(){return ' +
    'A}),n.d(t,"Ne",function(){return w}),n.d(t,"hc",function(){return ' +
    'D}),n.d(t,"oc",function(){return C}),n.d(t,"Tb"\n\nTypeError: ' +
    'window.matchMedia is not a function\n    at Object.74 ' +
    '(/app/static/js/main.37608af7.chunk.js:1:439512)\n    at d ' +
    '(https://app.showhow.nz/:1:938)\n    at Object.84 ' +
    '(/app/static/js/main.37608af7.chunk.js:1:441839)\n    at d ' +
    '(https://app.showhow.nz/:1:938)\n    at Module.1498 ' +
    '(/app/static/js/main.37608af7.chunk.js:1:65008)\n    at d ' +
    '(https://app.showhow.nz/:1:938)\n    at Object.649 ' +
    '(/app/static/js/main.37608af7.chunk.js:1:434514)\n    at d ' +
    '(https://app.showhow.nz/:1:938)\n    at l (https://app.showhow.nz/:1:799)\n
 ' +
    '   at Array.e [as push] (https://app.showhow.nz/:1:662)'
}
/app/static/js/main.37608af7.chunk.js:1
(self.webpackJsonp=self.webpackJsonp||[]).push([[1],{1:function(e,t,n){"use stri
ct";n.d(t,"ob",function(){return r}),n.d(t,"d",function(){return a}),n.d(t,"jd",
function(){return o}),n.d(t,"I",function(){return s}),n.d(t,"Jd",function(){retu
rn c}),n.d(t,"lc",function(){return u}),n.d(t,"bf",function(){return d}),n.d(t,"
kc",function(){return l}),n.d(t,"af",function(){return f}),n.d(t,"a",function(){
return h}),n.d(t,"gd",function(){return b}),n.d(t,"Sc",function(){return p}),n.d
(t,"Gf",function(){return m}),n.d(t,"gc",function(){return g}),n.d(t,"xf",functi
on(){return v}),n.d(t,"Oc",function(){return E}),n.d(t,"Cf",function(){return O}
),n.d(t,"Nc",function(){return _}),n.d(t,"Bf",function(){return y}),n.d(t,"Nb",f
unction(){return S}),n.d(t,"Le",function(){return j}),n.d(t,"Ob",function(){retu
rn T}),n.d(t,"Me",function(){return I}),n.d(t,"Pb",function(){return A}),n.d(t,"
Ne",function(){return w}),n.d(t,"hc",function(){return D}),n.d(t,"oc",function()
{return C}),n.d(t,"Tb"

TypeError: window.matchMedia is not a function
    at Object.74 (/app/static/js/main.37608af7.chunk.js:1:439512)
    at d (https://app.showhow.nz/:1:938)
    at Object.84 (/app/static/js/main.37608af7.chunk.js:1:441839)
    at d (https://app.showhow.nz/:1:938)
    at Module.1498 (/app/static/js/main.37608af7.chunk.js:1:65008)
    at d (https://app.showhow.nz/:1:938)
    at Object.649 (/app/static/js/main.37608af7.chunk.js:1:434514)
    at d (https://app.showhow.nz/:1:938)
    at l (https://app.showhow.nz/:1:799)
    at Array.e [as push] (https://app.showhow.nz/:1:662)

``

**Comment by chrisplatorres** [comment]
related issue https://github.com/exokitxr/exokit/issues/1202 and PR #799

**Comment by modulesio** [comment]
With this PR, we get a different error, but it's probably a separate missing class:

ReferenceError: DOMTokenList is not defined
    at /app/static/js/4.7c82664e.chunk.js:1:2546945
    at Object.<anonymous> (/app/static/js/4.7c82664e.chunk.js:1:2547110)
    at r (/app/static/js/4.7c82664e.chunk.js:1:2529867)
    at Object.<anonymous> (/app/static/js/4.7c82664e.chunk.js:1:2533769)
    at r (/app/static/js/4.7c82664e.chunk.js:1:2529867)
    at Object.<anonymous> (/app/static/js/4.7c82664e.chunk.js:1:2530714)
    at r (/app/static/js/4.7c82664e.chunk.js:1:2529867)
    at /app/static/js/4.7c82664e.chunk.js:1:2530668
    at o (/app/static/js/4.7c82664e.chunk.js:1:2530677)
    at Object.<anonymous> (/app/static/js/4.7c82664e.chunk.js:1:2842559)
