### ISSUE TITLE
DOMTokenList is not defined

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#1206]
Looks like we need to implement https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList

```
$ node . -x webvr https://app.showhow.nz/
...
ReferenceError: DOMTokenList is not defined
    at /app/static/js/4.7c82664e.chunk.js:1:2546945
    at Object.<anonymous> (/app/static/js/4.7c82664e.chunk.js:1:2547110)
    at r (/app/static/js/4.7c82664e.chunk.js:1:2529867)
    at Object.<anonymous> (/app/static/js/4.7c82664e.chunk.js:1:2533769)
    at r (/app/static/js/4.7c82664e.chunk.js:1:2529867)
    at Object.<anonymous> (/app/static/js/4.7c82664e.chunk.js:1:2530714)
    at r (/app/static/js/4.7c82664e.chunk.js:1:2529867)
    at /app/static/js/4.7c82664e.chunk.js:1:2530668
    at o (/app/static/js/4.7c82664e.chunk.js:1:2530677)
    at Object.<anonymous> (/app/static/js/4.7c82664e.chunk.js:1:2842559)
```

Follow up from https://github.com/exokitxr/exokit/issues/1204.

**Comment by modulesio** [comment]
Exokit currently has a [hacky return value for ClassList](https://github.com/exokitxr/exokit/blob/36e9b6a2f223e5fadea6a69167aa8fb331a3f2b9/src/DOM.js#L914) -- it should be an actual `DOMTokenList` per spec.
