### ISSUE TITLE
"Window destoyed" warning on starting A-Painter

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#1207]
```$ node .
[x] https://aframe.io/a-painter/
Thrown:
Error: cancel request: window destroyed
    at WorkerVm.destroy (C:\Users\chris\github\exokit\src\WindowVm.js:203:19)
    at WorkerVm.<anonymous> (C:\Users\chris\github\exokit\src\WindowVm.js:181:12
)
    at WorkerVm.emit (events.js:200:13)
    at WorkerVm.EventEmitter.emit (domain.js:471:20)
    at Worker._message (C:\Users\chris\github\exokit\src\WindowVm.js:39:16)
    at Worker.emit (events.js:200:13)
    at Worker.EventEmitter.emit (domain.js:471:20) {
  code: 'ECANCEL'
}
[x] A-Frame Version: 0.7.0 (Date 2018-02-05, Commit #39daf67)
three Version: github:dmarcos/three.js#r89fix
WebVR Polyfill Version: ^0.9.40
core:schema:warn Default value `0 1 0` does not match type `vec3` in component `
teleport-controls```

C.f. https://github.com/exokitxr/exokit/blob/fc85e86d61641aa332ceee9cb24827665e4bc72b/src/WindowVm.js#L207

My initial thought is that we can simply get rid of this warning -- it just means the window was destroyed while it was in the middle of a `requestAnimationFrame`, which is not strictly an error.

**Comment by modulesio** [comment]
Looks like this one happens only coming from CLI mode -- launching directly into painter works:

```
$ node . -x webvr https://aframe.io/a-painter/
A-Frame Version: 0.7.0 (Date 2018-02-05, Commit #39daf67)
```
