### ISSUE TITLE
Self signed certificate for dev

### ISSUE THREAD

**Issue by bknill** [exokitxr/exokit#1211]
This isn't a bug - but helpful for development. 

I'm using a self signed certificate for a local development server.  Running in Exokit throws this error: 

```
FetchError: request to https://localhost:3000/ failed, reason: self signed certificate
    at ClientRequest.<anonymous> (/home/owner/workspace/exokit/exokit/node_modules/window-fetch/lib/index.js:1290:16)
    at ClientRequest.emit (events.js:196:13)
    at ClientRequest.EventEmitter.emit (domain.js:471:20)
    at TLSSocket.socketErrorListener (_http_client.js:409:9)
    at TLSSocket.emit (events.js:196:13)
    at TLSSocket.EventEmitter.emit (domain.js:471:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  message: 'request to https://localhost:3000/ failed, reason: self signed certificate',
  type: 'system',
  errno: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```
If possible, it can be overcome with something like this:

```
const agent = new https.Agent({
  rejectUnauthorized: false
})
fetch(myUrl, { agent })
```

Is it possible that Exokit could handle self signed certificates for development or is that not an option?

**Comment by modulesio** [comment]
You can accept insecure https with this flag: https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

It’s more a node thing than an exokit thing.

**Comment by modulesio** [comment]
```
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

Should do the trick, so closing this issue as resolved.
