### ISSUE TITLE
Invalid URL: ws:///

### ISSUE THREAD

**Issue by shawwn** [exokitxr/exokit#1243]
`node . ./examples/geometry_client.html` results in:

```
TypeError [ERR_INVALID_URL]: Invalid URL: ws:///
    at onParseError (internal/url.js:241:9)
    at new URL (internal/url.js:317:5)
    at initAsClient (/Users/emily/exokit-june/node_modules/ws/lib/websocket.js:484:27)
    at new WebSocket (/Users/emily/exokit-june/node_modules/ws/lib/websocket.js:70:7)
    at file:///Users/emily/exokit-june/examples/geometry_client.html:897:14
    at file:///Users/emily/exokit-june/examples/geometry_client.html:1138:3
    at Script.runInThisContext (vm.js:124:20)
    at Object.runInThisContext (vm.js:314:38)
    at /Users/emily/exokit-june/src/DOM.js:1855:12
    at Resource.ownerDocument.resources.addResource [as getCb] (/Users/emily/exokit-june/src/DOM.js:1860:9)
```
Seems like exokit's URL handling is less forgiving than Chrome.

I guess it's not technically a bug since the url is nonconforming, but I'm reporting whatever errors I see.

**Comment by modulesio** [comment]
That example is not expected to be loaded in Exokit, but the parse error is indeed a bug.

**Comment by modulesio** [comment]
This looks correct; when loaded from a `file://` URL that example will have no host to refer to for its Web Socket.

That example is not intended to be loaded into Exokit, or to be loaded from `file://`. It is part of another example, where it is served to non-exokit clients.
