### ISSUE TITLE
TypeError: Cannot read property 'customElements' of undefined - html2Canvas

### ISSUE THREAD

**Issue by bknill** [exokitxr/exokit#1254]
I've seen a few issues mention CustomElements, however I'm not sure if they're resolved. 

We make extensive use of [html2canvas](https://github.com/niklasvh/html2canvas) for rendering SVGs etc in 3D. 

I'm getting this error: 

```
Failure loading node:   TypeError: Cannot read property 'customElements' of undefined
    at new HTMLElement (/home/owner/workspace/client/exokit/src/DOM.js:1352:30)
    at new DocumentFragment (/home/owner/workspace/client/exokit/src/Document.js:520:5)
    at new Range (/home/owner/workspace/client/exokit/src/Document.js:532:5)
    at Document.document.createRange (/home/owner/workspace/client/exokit/src/Document.js:71:32)
    at Support.testRangeBounds (/static/js/7.chunk.js:1493:24)
    at new Support (/static/js/7.chunk.js:1480:29)
    at renderNode (/static/js/7.chunk.js:1378:19)
    at html2canvas (/static/js/7.chunk.js:1342:12)
    at NewShader.__render (/static/js/7.chunk.js:1236:26)
    at NewShader.__ready (/static/js/7.chunk.js:1272:12)
    at NewShader.__setTexure (/static/js/7.chunk.js:952:14)
    at NewShader.__validateSrc (/static/js/7.chunk.js:1074:11)
    at NewShader.__updateTexture (/static/js/7.chunk.js:1039:14)
    at NewShader.update (/static/js/7.chunk.js:879:12)
```
Does this mean CustomElements and Html2Canvas are not supported? 

Thanks

**Comment by bknill** [comment]
Updated and this is fixed.

**Comment by modulesio** [comment]
> Does this mean CustomElements and Html2Canvas are not supported?

`CustomElements` are supported, but `html2canvas` wouldn't be.

Exokit supports full 2D iframe rendering via electron, but does not support the `<svg>` rendering trick.

**Comment by bknill** [comment]
OK thanks is there any documentation around 2D to textures? 

Does this mean the SVGs need to be pre-rendered?

**Comment by modulesio** [comment]
> OK thanks is there any documentation around 2D to textures?

No, but there are examples: https://github.com/exokitxr/exokit/blob/351cd5ca671ac2b1569f80ef1f6af317b2ad8f6c/examples/browser.html#L77

A 2d iframe has a `.texture` which is the live rendering of the content that can be used in the scene.

> Does this mean the SVGs need to be pre-rendered?

No, svgs themselves should be ok. However, the external content hack for svgs as used by `html2canavs` will not work since it's not really rendering svg's.

**Comment by bknill** [comment]
OK that's great thanks. 

Quick question, I have around 100 icons I want to render and be available to the scene that are currently SVGs. Am I best to dynamically create an IFRAME for each one and render that, or create some kind of sprite sheet for all the icons in an IFRAME and render and crop that. - creating an iframe for each one is easier, I just don't know if that's going to have a performance hit. 

Pre-rendering them as PNGs in the Web app is also a possibility.

**Comment by modulesio** [comment]
The prerendered sprite sheet will be the fastest way, performance-wise. It's probably not a good idea to have 100 iframes, though it could work if it was packed into a single iframe.
