### ISSUE TITLE
Error when loading realitytabs.html example

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#1389]
Windows 10
Node v12.4.0
Exokit built from source

Exokit loads a window, but the window is blank/white and has the below error:

```
$ node . examples/realitytabs.html
THREE.WebGLRenderer 105





    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:126:23) {
  code: 108
}
```
![blankkCapture](https://user-images.githubusercontent.com/29695350/62671240-ae5cf180-b95b-11e9-8364-39202d609cdc.PNG)

**Comment by modulesio** [comment]
As far as I know Exokit Windows cannot be loaded from Bash.

**Comment by chrisplatorres** [comment]
might be a duplicate of #524 / #968 

more error:
```
Error: Hmd Not Found (108)
    at _waitHandleRequest (C:\Users\chris\github\exokit\src\index.js:442:50)
    at _waitHandleRequests (C:\Users\chris\github\exokit\src\index.js:396:5)
    at Immediate._topRenderLoop (C:\Users\chris\github\exokit\src\index.js:1269:
5)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:126:23) {
  code: 108
}
```

**Comment by modulesio** [comment]
Ah yeah, it could also be that. The console weirdness I would attribute to running a windows app in Linux.

**Comment by chrisplatorres** [comment]
Issue was solved by uninstalling [ALVR](https://github.com/polygraphene/ALVR) drivers.
