### ISSUE TITLE
Linux + SteamVR: VRCompositorError_TextureUsesUnsupportedFormat

### ISSUE THREAD

**Issue by SketchStick** [exokitxr/exokit#1412]
**Describe the bug**
Trying to run Exokit with SteamVR under Linux and just got this error with black being displayed in the window, nothing presenting in the headset (evident by the default steamvr environment) but "node" being noted in the vrmonitor.

> Error: Compositor error: VRCompositorError_TextureUsesUnsupportedFormat
>     at _submitFrame (/home/sketchstick/apps/exokit/exokit/src/index.js:1224:42)
>     at Immediate._topRenderLoop (/home/sketchstick/apps/exokit/exokit/src/index.js:1319:11)
 
**To Reproduce**
Shows in the terminal upon running.

**Additional context**
The build/run scripts and their terminal output: https://gist.github.com/SketchStick/b359e1d97625d9182819801b50d98865

**System information:**
 - OS: Arch Linux x86 64-bit
 
 - Exokit Version: Git Master
 
 - Node version: v12.2.0, binary grabbed from the official site and run directly without anything managing the environment (eg. nvm), which could be problematic under certain circumstances.
 
 - Npm version: 6.9.0
 
 - Is your Exokit downloaded or built? Built.

**Comment by jcc10** [comment]
Just wanted to add my experience and data.

The home menu will flash open and closed fast enough that I can't kill the app through it and must instead restart SteamVR, background is all black, and the VR Monitor shows node being the app running.

System Information:
* OS: Pop!_OS 19.10 (Ubuntu derivative)
* Exokit Version: Git Master
* Node version: v12.16.1 via nvm
* Npm version: 6.13.4
* Is your Exokit downloaded or built? Built.
* SteamVR version: 1.11.4 (Steam VR Beta)
* HMD: Valve Index (Probably not relevant)
* GPU: GeForce RTX 2080 Ti
* Driver: nvidia-driver-440 - 440.44

I just want one program to be able to run WebVR/WebXR on my HMD on Linux. :cry: 

Tell me if any more information is needed as I would love to see this get to a usable state.

**Comment by oxr463** [comment]
Any luck on this one?
