### ISSUE TITLE
WebXR: monochrome

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#292]
This WebXR sample renders in monochrome: https://immersive-web.github.io/webxr-samples/room-scale.html

![capture 12](https://user-images.githubusercontent.com/6926057/43560081-dd15b42c-95de-11e8-91ee-7e479115a0ed.PNG)

Should be more like:

![capture 13](https://user-images.githubusercontent.com/6926057/43560122-0df64a5c-95df-11e8-85dc-c38fc840a643.PNG)

**Comment by chrislatorres** [comment]
System info:  
Exokit v0.0.520

I am getting `ReferenceError: XRFrame is not defined`

```
/exokit$ node . https://immersive-web.github.io/webxr-samples/room-scale.html
[WebXR version shim] Installing navigator.xr.requestSession shim.
[WebXR version shim] Installing navigator.xr.supportsSessionMode shim.
[WebXR version shim] Installing XRSession.requestReferenceSpace shim.
ReferenceError: XRFrame is not defined
    at WebXRVersionShim._applyPatch (js/webxr-version-shim.js:308:28)
    at new WebXRVersionShim (js/webxr-version-shim.js:140:12)
    at https://immersive-web.github.io/webxr-samples/room-scale.html:72:25
    at https://immersive-web.github.io/webxr-samples/room-scale.html:205:9
    at Object._runJavascript (/home/chris/github/exokit/src/utils.js:71:15)
    at Resource.ownerDocument.resources.addResource [as getCb] (/home/chris/github/exokit/src/DOM.js:1700:13)
    at Promise (/home/chris/github/exokit/src/core.js:110:12)
    at new Promise (<anonymous>)
    at Resource.get (/home/chris/github/exokit/src/core.js:109:12)
    at Resources.drain (/home/chris/github/exokit/src/core.js:188:16)
```

**Comment by modulesio** [comment]
☝️ That one is probably because the WebXR spec changed and the implementation needs to be updated. THREE.js covers over that but the samples to not.

**Comment by modulesio** [comment]
This is rendering fine as of https://github.com/exokitxr/exokit/pull/1151.

I don't know what it was, bug we've fixed plenty of WebGL since this test. Closing as fixed.
