### ISSUE TITLE
Unity WebVR Export Support

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#453]
URL: `https://mozilla.github.io/unity-webvr-export/`

Ran on:
Ubuntu 18.04
Exokit 0.0.452

Got this error when running the Unity WebVR Export demo. 
https://github.com/mozilla/unity-webvr-export

```
$ exokit https://mozilla.github.io/unity-webvr-export/Build/
SyntaxError: Unexpected token true
    at Function (<anonymous>)
    at selectorFn (/usr/local/lib/exokit/node_modules/window-selector/selector.js:38:25)
    at Object.matches (/usr/local/lib/exokit/node_modules/window-selector/selector.js:100:18)
    at HTMLElement.matches (/usr/local/lib/exokit/src/DOM.js:832:21)
    at selectors.some.selector (/usr/local/lib/exokit/core.js:1126:60)
    at Array.some (<anonymous>)
    at window.getComputedStyle.el (/usr/local/lib/exokit/core.js:1126:40)
    at n (Build/UnityLoader.js:4:8746)
    at Document.<anonymous> (Build/UnityLoader.js:4:11667)
    at Document.emit (events.js:182:13)
    at Document.EventEmitter.emit (domain.js:442:20)
    at Document._emit (/usr/local/lib/exokit/src/Event.js:56:40)
    at _emit (/usr/local/lib/exokit/src/Event.js:34:14)
    at _recurse (/usr/local/lib/exokit/src/Event.js:42:7)
    at Document.dispatchEvent (/usr/local/lib/exokit/src/Event.js:52:5)
    at process.nextTick (/usr/local/lib/exokit/src/Document.js:163:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by shaneharris** [comment]
I will debug this later and see what caused it. It might be out of scope if there are special dom elements being used.

**Comment by modulesio** [comment]
If it works in a browser then I'd say it's in scope for being supported, as long as it's not depending on 2D DOM rendering.

**Comment by modulesio** [comment]
Basic Unity exports work in Exokit now.

**Comment by modulesio** [comment]
The errant selector for the above is `[data-unity-loaded='true'] #loader`

**Comment by modulesio** [comment]
With that fix, Unity exports should be running fine in Exokit:

![Capture 31](https://user-images.githubusercontent.com/6926057/60847914-7faff780-a1b2-11e9-9ea8-bf7199dd1b70.PNG)
