### ISSUE TITLE
Mozilla Hubs on magic leap

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#595]
Debugging link: hub.link/izsgtf8

**Comment by paperkettle** [comment]
Tried a hubs URL on Magic Leap with query string `vr_entry_type=vr_now` which theoretically might boot one right into hubs

and get the error posted below

I have my own local fork of hubs running as well, happy to tinker with client code as this progresses

https://github.com/exokitxr/exokit/issues/810#issuecomment-483463708

```
04-17 22:20:12.651  1898     2 I exokit  : ---------------------exokit start
04-17 22:20:12.651  1898     2 I exokit  : get arg 0: node
04-17 22:20:12.651  1898     2 I exokit  : get arg 1: --experimental-worker
04-17 22:20:12.651  1898     2 I exokit  : get arg 2: .
04-17 22:20:12.651  1898     2 I exokit  : get arg 3: -x
04-17 22:20:12.651  1898     2 I exokit  : get arg 4: webvr
04-17 22:20:12.651  1898     2 I exokit  : get arg 5: https://hubs.mozilla.com/lx76D3H/remote-wide-spot?vr_entry_type=vr_now
04-17 22:20:15.753  1898     3 E exokit  : __bionic_open_tzdata_path: ANDROID_DATA not set!
04-17 22:20:19.055  1898     2 I exokit  : A-Frame Version: https://github.com/MozillaReality/aframe
04-17 22:20:19.055  1898     2 I exokit  : three Version: https://github.com/MozillaReality/three.js
04-17 22:20:19.137  1898     2 I exokit  : core:schema:warn Default value `null` does not match type `string` in component `media-loader` 
04-17 22:20:19.218  1898     2 I exokit  : core:schema:warn Default value `null` does not match type `string` in component `camera-focus-button` 
04-17 22:20:19.226  1898     2 I exokit  : core:schema:warn Default value `null` does not match type `string` in component `emit-scene-event-on-remove` 
04-17 22:20:19.372  1898     2 I exokit  : core:schema:warn Default value `false` does not match type `string` in component `vr-mode-toggle-class` 
04-17 22:20:19.416  1898     2 I exokit  : Hubs version: 729 (926f6c2462930b6062549a9bcb0f980e7e35fb07)
04-17 22:20:19.495  1898     2 I exokit  : Tracking: Sentry DSN: https://013d6a364fed43cdb0539a61d520597a@sentry.prod.mozaws.net/370
04-17 22:20:19.507  1898     2 I exokit  : Tracking: Google Analytics ID: UA-77033033-12
04-17 22:20:20.168  1898     2 I exokit  : Using WebGL 2.0 context.
04-17 22:20:20.170  1898     2 I exokit  : THREE.WebGLRenderer 103
04-17 22:20:20.222  1898     2 I exokit  : Using Non-VR bindings.
04-17 22:20:20.223  1898     2 I exokit  : Using Non-VR bindings.
04-17 22:20:20.223  1898     2 I exokit  : Using Non-VR bindings.
04-17 22:20:21.363  1898     2 I exokit  : Hub ID: b5K85YN
04-17 22:20:21.681  1898     3 E exokit  : [mp3 @ 0x400047ec3e00] Format mp3 detected only with low score of 25, misdetection possible!
04-17 22:20:21.890  1898     3 E exokit  : [mp3 @ 0x40004a8e3800] Format mp3 detected only with low score of 5, misdetection possible!
04-17 22:20:21.905  1898     3 E exokit  : [mp3 @ 0x40004a8e3800] Format mp3 detected only with low score of 25, misdetection possible!
04-17 22:20:23.944  1898     2 I exokit  : core:a-assets:warn Asset loading timed out in   3000 ms
04-17 22:20:25.383  1898     2 I exokit  : THREE.GLTFLoader: Duplicating UVs to support aoMap.
04-17 22:20:25.672  1898     2 I exokit  : frameworks/perception/src/perception_context.cpp(275) DoStartup():
04-17 22:20:25.672  1898     2 I exokit  : ALW: [ LLComm ] Obtained frame time handle, using wearable pose timestamps.
04-17 22:20:26.078  1898     2 I exokit  : frameworks/perception/src/trackers/ihead_tracker.cpp(56) IHeadTracker():
04-17 22:20:26.078  1898     2 I exokit  : ALW: reason=idGenerated,source="Head",for=world,id="{a3488416-538f-7018-bf0d-23c4139e8724}"
04-17 22:20:26.078  1898     2 I exokit  : frameworks/perception/src/trackers/ieye_tracker.h(61) IEyeTracker():
04-17 22:20:26.078  1898     2 I exokit  : ALW: reason=idGenerated,source="Eye",for=fixation,id="{f3f55b2e-12e0-7018-bfd9-9bac644b06cd}"
04-17 22:20:26.078  1898     2 I exokit  : frameworks/perception/src/trackers/ieye_tracker.h(63) IEyeTracker():
04-17 22:20:26.078  1898     2 I exokit  : ALW: reason=idGenerated,source="Eye",for=left_center,id="{2e3dec65-883c-7018-8d6d-8683f1bcd0b1}"
04-17 22:20:26.078  1898     2 I exokit  : frameworks/perception/src/trackers/ieye_tracker.h(65) IEyeTracker():
04-17 22:20:26.078  1898     2 I exokit  : ALW: reason=idGenerated,source="Eye",for=right_center,id="{c4210089-1f2c-7018-b065-8e41d0d6a71c}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=0,id="{41464462-0de2-7018-bd15-a7ec7c83fb9f}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=1,id="{139a7f4b-0c42-7018-8dc4-4f9c3635cf3b}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=2,id="{1fa5bf87-7fc9-7018-9371-282c773eab02}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=3,id="{2dbce549-5011-7018-a1e2-f2f78083980c}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=4,id="{48121eee-a02b-7018-aeef-eba9da0034f4}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=5,id="{eae66578-a58f-7018-96e2-35e2bde17307}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=6,id="{d580bc80-c881-7018-83fa-44016d3054ce}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=7,id="{185ce8fb-843d-7018-9e3e-47a79ce3d4e3}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=8,id="{14d014b1-7ab6-7018-8c37-b3900d965354}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=9,id="{149dd945-0900-7018-a3ed-2fdf7f877315}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=10,id="{acab6810-e3c8-7018-9e3a-2d3484cf1c89}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=11,id="{34a4afe5-a585-7018-9db5-c71658841713}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=12,id="{a917c5f6-53ae-7018-9a8d-6d5c13b74b7c}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=13,id="{732e9948-ea7b-7018-9e3c-9ab633f7a1cb}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=14,id="{0d3e2e49-8d0f-7018-a583-c5a22fb168f6}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=15,id="{15800539-ae75-7018-b3d2-7cb66566a1be}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=16,id="{81f036a8-6d2e-7018-9e23-caa873c2fcc2}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=17,id="{d1662de1-d237-7018-8fa2-2ef850f2414d}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=18,id="{7c09c2e1-c288-7018-be5c-8ea57d64ac4d}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=19,id="{39c9ae8f-635c-7018-83dd-18078b481001}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=20,id="{d1b9a6c9-b22c-7018-9e01-a43e9ceb7190}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=21,id="{aaa51b14-6560-7018-ab19-195417508157}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=22,id="{c7f721a4-2618-7018-a916-bcfa8cf05ed9}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=23,id="{78efe740-fbf1-7018-8b99-f445dead5e27}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=24,id="{29f69726-ee1c-7018-a941-58951b91b128}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=25,id="{5c428578-bf78-7018-8dc2-22814d80c409}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=26,id="{4b164481-5297-7018-a5ca-36a28de2eaac}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=27,id="{a5c464e2-b955-7018-9f35-8ed393f16f1c}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=28,id="{01703adc-6c09-7018-a5b1-c0dd3c8e53a5}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=29,id="{e4183f45-07f9-7018-8a29-d8981720e24c}"
04-17 22:20:27.758  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.758  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=30,id="{f6e9ab00-f44b-7018-8ff6-925249ede5d8}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=31,id="{b12e9d87-64e0-7018-a7b4-3a98f6c2d0ac}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=32,id="{8ef9105d-f982-7018-801c-5ee68b1f9532}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=33,id="{95b56bcb-b02b-7018-abef-112239470d40}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=34,id="{7a7280ab-1b87-7018-a3df-3959386816bb}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=35,id="{91a5ab86-d7b5-7018-a68e-54a73f52b7a2}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=36,id="{e991a6c2-6c67-7018-8aa5-bd3108818d4e}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=37,id="{d5ae82c4-eec1-7018-b25e-44bba54c3736}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=38,id="{759ad751-9b30-7018-8573-e546d557e13a}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=39,id="{e2ebebd3-aaed-7018-a5d4-2b6715c786be}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=40,id="{aacad7e9-6f12-7018-885a-2ca51f9d9d0e}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=41,id="{1330eec7-8029-7018-bc0a-39c4d17a14ac}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=42,id="{0388bf11-67b8-7018-b67b-878fa520c8cc}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=43,id="{b81deb27-1a0c-7018-ae17-3d211332fa36}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=44,id="{a228bb5e-2ff2-7018-bb25-0533a52c8dbe}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=45,id="{3cb269bc-b437-7018-af7e-6a25b4177e67}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=46,id="{adf40e7e-7b28-7018-bd53-62db87f426ff}"
04-17 22:20:27.759  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(99) HandTracker():
04-17 22:20:27.759  1898     2 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=47,id="{91e4701c-bf5a-7018-8530-8e19b6208685}"
04-17 22:20:27.799  1898     2 I exokit  : Using VR bindings.
04-17 22:20:27.825  1898     2 I exokit  : frameworks/perception/src/perception_context.cpp(847) SetRigTransforms():
04-17 22:20:27.825  1898     2 I exokit  : ALW: Setting new rig transforms in perception_context
04-17 22:20:27.825  1898     2 I exokit  : frameworks/perception/src/trackers/calibration.cpp(994) Update():
04-17 22:20:27.825  1898     2 I exokit  : ALW: reason=processedUpdatedRigModel,timestamp=896698115000
04-17 22:20:27.825  1898     2 I exokit  : frameworks/libs/llcommcpp/llcomm_helpers/impl/llcomm_helpers.cpp(256) SafeQueryByTime():
04-17 22:20:27.825  1898     2 I exokit  : ERR: reason=llcomQueryError,handle_name=XVUjdJR_dYKV75,time_us=18446744073709551615,status=23=LLCOMM_PERMISSION_DENIED
04-17 22:20:27.825  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker_llcomm.cpp(288) Update():
04-17 22:20:27.825  1898     2 I exokit  : ERR: [ LLComm ] Failed to complete query for [ gesture_llcomm ].
04-17 22:20:28.042  1898     2 I exokit  : Pre-emptively exiting VR mode.
04-17 22:20:28.100  1898     3 E exokit  : Error: MLContext::PrepareFrame: invalid arguments
04-17 22:20:28.100  1898     3 E exokit  :     at Immediate._renderLoop (/package/src/index.js:1339:32)
04-17 22:21:27.123  1898     2 I exokit  : malleus/ml_binder/calibration/calibration_sub_client_binder.cpp(64) onRigModel():
04-17 22:21:27.123  1898     2 I exokit  : ALW: onRigModel got rig model buffer of size 503895
04-17 22:21:31.041  1898     2 I exokit  : malleus/ml_binder/calibration/calibration_sub_client_binder.cpp(64) onRigModel():
04-17 22:21:31.041  1898     2 I exokit  : ALW: onRigModel got rig model buffer of size 503895
04-17 22:21:33.081  1898     2 I exokit  : malleus/ml_binder/calibration/calibration_sub_client_binder.cpp(64) onRigModel():
04-17 22:21:33.081  1898     2 I exokit  : ALW: onRigModel got rig model buffer of size 503895
04-17 22:21:35.049  1898     2 I exokit  : malleus/ml_binder/calibration/calibration_sub_client_binder.cpp(64) onRigModel():
04-17 22:21:35.049  1898     2 I exokit  : ALW: onRigModel got rig model buffer of size 503895
04-17 22:21:52.832  1898     2 I exokit  : malleus/ml_binder/calibration/calibration_sub_client_binder.cpp(64) onRigModel():
04-17 22:21:52.832  1898     2 I exokit  : ALW: onRigModel got rig model buffer of size 503895
```

**Comment by chrisplatorres** [comment]
@paperkettle is this a release version of the MPK or built?

**Comment by paperkettle** [comment]
ah apologies, v0.0.520 .mpk from releases

**Comment by chrisplatorres** [comment]
Unable to debug because ML SDK download is down. It looks like it exits VR mode and then that causes an error in the render loop

```sh
04-17 22:20:27.825  1898     2 I exokit  : ERR: reason=llcomQueryError,handle_name=XVUjdJR_dYKV75,time_us=18446744073709551615,status=23=LLCOMM_PERMISSION_DENIED
04-17 22:20:27.825  1898     2 I exokit  : frameworks/perception/src/trackers/hand_tracker_llcomm.cpp(288) Update():
04-17 22:20:27.825  1898     2 I exokit  : ERR: [ LLComm ] Failed to complete query for [ gesture_llcomm ].
04-17 22:20:28.042  1898     2 I exokit  : Pre-emptively exiting VR mode.
04-17 22:20:28.100  1898     3 E exokit  : Error: MLContext::PrepareFrame: invalid arguments
04-17 22:20:28.100  1898     3 E exokit  :     at Immediate._renderLoop (/package/src/index.js:1339:32)
```

https://github.com/exokitxr/exokit/blob/master/src/index.js#L1558-L1563

**Comment by modulesio** [comment]
Folding this one into https://github.com/exokitxr/exokit/issues/810.
