### ISSUE TITLE
cancelAnimationFrame throws

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#790]
When passing a non-rafed frame to `cancelAnimationFrame`, it is possible for it to throw.

**Comment by modulesio** [comment]
```
03-01 10:26:16.175  1771     3 E exokit  : TypeError: Cannot read property 'Symbol()' of null
03-01 10:26:16.175  1771     3 E exokit  : TypeError: Cannot read property 'Symbol()' of null
03-01 10:26:16.175  1771     3 E exokit  : TypeError: Cannot read property 'Symbol()' of null
03-01 10:26:16.175  1771     3 E exokit  :     at rafCbs.findIndex.r (/package/src/Window.js:1002:42)
03-01 10:26:16.175  1771     3 E exokit  :     at rafCbs.findIndex.r (/package/src/Window.js:1002:42)
03-01 10:26:16.175  1771     3 E exokit  :     at rafCbs.findIndex.r (/package/src/Window.js:1002:42)
03-01 10:26:16.175  1771     3 E exokit  :     at Array.findIndex (<anonymous>)
03-01 10:26:16.175  1771     3 E exokit  :     at Array.findIndex (<anonymous>)
03-01 10:26:16.175  1771     3 E exokit  :     at Array.findIndex (<anonymous>)
03-01 10:26:16.175  1771     3 E exokit  :     at window.cancelAnimationFrame.id (/package/src/Window.js:1002:26)
03-01 10:26:16.175  1771     3 E exokit  :     at window.cancelAnimationFrame.id (/package/src/Window.js:1002:26)
03-01 10:26:16.175  1771     3 E exokit  :     at window.cancelAnimationFrame.id (/package/src/Window.js:1002:26)
```

**Comment by modulesio** [comment]
Closing as fixed.
