### ISSUE TITLE
Supercraft compatibility

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#806]
Exokit v0.0.517
Ubuntu 18.04 
Node v11.10.1

-----------------------------------------------------------------------

command ran:
`exokit  http://supermedium.com/craft/icky-snake`

-----------------------------------------------------------------------

complete log: https://gist.github.com/chrislatorres/21fc44ff23c23b5093c4dcf874bb25fd
  
```
chris@chris:~$ exokit  http://supermedium.com/craft/icky-snake
A-Frame Version: 0.8.2 (Date 2018-08-07, Commit #2f96417)
three Version: 0.95.0
WebVR Polyfill Version: ^0.10.5
core:schema:warn Default value `false` does not match type `number` in component `layout` 
core:schema:warn Default value `0 1 0` does not match type `vec3` in component `teleport-controls` 
THREE.WebGLRenderer 95
TypeError: e.vr.setPoseTarget is not a function
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:258:9392)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:258:3097)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:250:745)
    at m (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:28:1452)
    at l (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:28:80)
    at Document.f (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:28:786)
    at Document.emit (events.js:197:13)
    at Document.EventEmitter.emit (domain.js:446:20)
    at Document._emit (/usr/local/lib/exokit/src/Event.js:60:40)
    at _emit (/usr/local/lib/exokit/src/Event.js:38:14)
core:schema:warn Unknown property `height` for component/system `geometry`. 
core:a-node:error Failure loading node:   TypeError: Cannot read property 'subscribe' of undefined
    at AFRAME.components.(anonymous function).Component.init (build/build.js?v=1543876567239:1:12831)
    at AFRAME.components.(anonymous function).Component.init (build/build.js?v=1543876567239:1:7233)
    at AFRAME.components.(anonymous function).Component.updateProperties (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:252:3547)
    at AFRAME.components.(anonymous function).Component.module.exports.Component (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:252:1683)
    at AFRAME.components.(anonymous function).Component.i [as constructor] (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:252:6186)
    at new AFRAME.components.(anonymous function).Component (build/build.js?v=1543876567239:1:7258)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:4341)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:6018)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:5781)
    at https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:3619
core:a-node:error Failure loading node:   TypeError: Cannot read property 'subscribe' of undefined
    at AFRAME.components.(anonymous function).Component.init (build/build.js?v=1543876567239:1:12831)
    at AFRAME.components.(anonymous function).Component.init (build/build.js?v=1543876567239:1:7233)
    at AFRAME.components.(anonymous function).Component.updateProperties (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:252:3547)
    at AFRAME.components.(anonymous function).Component.module.exports.Component (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:252:1683)
    at AFRAME.components.(anonymous function).Component.i [as constructor] (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:252:6186)
    at new AFRAME.components.(anonymous function).Component (build/build.js?v=1543876567239:1:7258)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:4341)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:6018)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:5781)
    at https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:3619
core:a-node:error Failure loading node:   TypeError: Cannot read property 'subscribe' of undefined
    at AFRAME.components.(anonymous function).Component.init (build/build.js?v=1543876567239:1:12831)
    at AFRAME.components.(anonymous function).Component.init (build/build.js?v=1543876567239:1:7233)
    at AFRAME.components.(anonymous function).Component.updateProperties (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:252:3547)
    at AFRAME.components.(anonymous function).Component.module.exports.Component (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:252:1683)
    at AFRAME.components.(anonymous function).Component.i [as constructor] (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:252:6186)
    at new AFRAME.components.(anonymous function).Component (build/build.js?v=1543876567239:1:7258)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:4341)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:6018)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:5781)
    at https://rawgit.com/aframevr/aframe/8e5f7b3/dist/aframe-master.min.js:244:3619
```

**Comment by modulesio** [comment]
Thanks!

For A-Frame in particular, if we're logging errors, we should also try `-x webvr` to disable WebXR, and also try with an unminified build (locally if needed).

**Comment by chrislatorres** [comment]
Forgot about `-x webvr`. When ran with the flag, there is a crash from: `TypeError [ERR_WORKER_UNSUPPORTED_OPERATION]: process.chdir() is not supported in workers`

```
$  exokit -x webvr http://supermedium.com/craft/icky-snake
A-Frame Version: 0.8.2 (Date 2018-08-07, Commit #2f96417)
three Version: 0.95.0
WebVR Polyfill Version: ^0.10.5
core:schema:warn Default value `false` does not match type `number` in component `layout` 
core:schema:warn Default value `0 1 0` does not match type `vec3` in component `teleport-controls` 
THREE.WebGLRenderer 95
HEY
core:schema:warn Unknown property `height` for component/system `geometry`. 
THREE.ExtrudeBufferGeometry: amount has been renamed to depth.
OBJLoader: 4.202ms
core:schema:warn Unknown property `color` for component/system `material`. 
TypeError [ERR_WORKER_UNSUPPORTED_OPERATION]: process.chdir() is not supported in workers
    at process.unavailableInWorker [as chdir] (internal/process/worker_thread_only.js:50:11)
    at /usr/local/lib/exokit/src/native-bindings.js:6:11
    at Object.<anonymous> (/usr/local/lib/exokit/src/native-bindings.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Bugsnag:  Encountered an uncaught error, terminating…
TypeError [ERR_WORKER_UNSUPPORTED_OPERATION]: process.chdir() is not supported in workers
    at process.unavailableInWorker [as chdir] (internal/process/worker_thread_only.js:50:11)
    at /usr/local/lib/exokit/src/native-bindings.js:6:11
    at Object.<anonymous> (/usr/local/lib/exokit/src/native-bindings.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

--------------------------------------------------------------------

When ran locally there is no crash, but there are errors from missing assets (can't find a public repo to pull full site from) : `exokit -x webvr /home/chris/Documents/Supercraft.html`

full log: https://gist.github.com/chrislatorres/1140ac0c5696304bd643adea7a658b74
```
   "ENOENT: no such file or directory, open '/home/chris/Documents/assets/img/menuIcons.svg'",
```

**Comment by modulesio** [comment]
Since it rewrites workers to be native node workers, I wonder how much of this is going to be fixed in the `user-parallel` update...

**Comment by chrislatorres** [comment]
note: the default supercraft site loads on desktop with 
`node .  -x webvr http://supermedium.com/craft/`


I guess it is this specific supercraft site causing the error:
`node .  -x webvr http://supermedium.com/craft/icky-snake`

**Comment by chrisplatorres** [comment]
Some Supercraft related fixes from: #1091 , #1092, #1093 

The above errors are fixed, now getting on latest master with `node . -x webvr  -t http://supermedium.com/craft/icky-snake`:
```
RangeError: Maximum call stack size exceeded
    at C:\Users\chris\github\exokit\src\Worker.js:67:28
    at emit (events.js:196:13)
    at C:\Users\chris\github\exokit\src\Worker.js:63:10
    at C:\Users\chris\github\exokit\src\Worker.js:69:12
    at emit (events.js:196:13)
    at C:\Users\chris\github\exokit\src\Worker.js:63:10
    at C:\Users\chris\github\exokit\src\Worker.js:69:12
    at emit (events.js:196:13)
    at C:\Users\chris\github\exokit\src\Worker.js:63:10
    at C:\Users\chris\github\exokit\src\Worker.js:69:12
````

![supCapture](https://user-images.githubusercontent.com/29695350/58198241-7f57ad80-7c93-11e9-89a4-36544ef4f52e.PNG)

**Comment by modulesio** [comment]
Runs well in create mode.

However, loading a template site has frustum culling issues. It seems to load, but the culling bounds on the loaded objects make them pop in and out of existence.

![Capture 26](https://user-images.githubusercontent.com/6926057/58212959-8a740300-7cbe-11e9-8fb8-2c59879afd5e.PNG)

**Comment by modulesio** [comment]
Another bug: the templates list does not track the templates clicked correctly. That is, you won't get the template you clicked, but one possibly from another template "page".

Though it's hard to see what you've actually loaded do to the above object culling issue 🤔.

**Comment by modulesio** [comment]
I haven't seen the culling issue lately, and compatibility here has drastically improved with recent releases.

Closing this issue as resolved. If there are specific new bugs, we can open new threads for it.
