### ISSUE TITLE
Error: Cannot find module './build/Release/vm_one.node' 

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#911]
Similar to #720 

Ran on clean ubuntu subsystem in Windows 10 after cloning Exokit with Node v11.6/npm 6.5.0-next.0
```sh
npm install
node .
```

Led to errors:
`Error: <.so name>: cannot open shared object file: No such file or directory`
for the following:
```
libnss3-dev
libxcomposite-dev
libxtst6
libxss-dev
libpangocairo-1.0-0
libatk1.0-dev
libatk-bridge2.0-0
```
installed those through apt^

--------------------------------------------------

Now getting:
`Error: Cannot find module './build/Release/vm_one.node'`

```sh
$ ls build/Release/
exokit.node  obj.target
```

**Comment by modulesio** [comment]
Running in WSL was never a supported option.

That said, the above looks like there was a build failure that was ignored and `node_modules` contains the failure. Can you wipe `node_modules` and try again?

**Comment by chrisplatorres** [comment]
No longer getting vm_one.node error after running `npm run rebuild` (wipe node_modules and cache then install),

now when running `node .` 

```sh
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/chris/github/exokit/node_modules/worker-native/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```
from https://github.com/modulesio/worker-native/blob/master/index.js#L3 

there are no files when searching for worker_threads

----------------------------------------------------

Also, I have 2 separate clones: one on WSL/ubuntu and other on windows being accessed through the git bash, they are both giving the error:
`Error: Cannot find module 'worker_threads'`

**Comment by modulesio** [comment]
That means that `--experimental-worker` was not passed into node. Can you try with? (before the `.`)

**Comment by chrisplatorres** [comment]
Yes that works for both clones, thanks.
