### ISSUE TITLE
Failed to load Cryptovoxels

### ISSUE THREAD

**Issue by madjin** [exokitxr/exokit#951]
**Describe the bug**
 What happened, and what did you expect to happen?
 Run `node --experimental-worker . https://cryptovoxels.com/play` and get an error that: `ReferenceError: HTMLBodyElement is not defined`
 
**To Reproduce**
Steps or commands ran to reproduce the behavior:
1. Go to 'terminal (MINGW64)'
2. Type `node --experimental-worker . https://cryptovoxels.com/play`
3. See error

**Additional context**
If you walk or fly around the city the url changes, might be of use to know this to test urls related to cryptovoxels.

**System information:**
 - OS: Windows 10
 
 - Exokit Version: d38467d
 
 - Node version: v11.6.0
 
 - Npm version/build log if applicable
 
 - Is your Exokit downloaded or built?
Built from source

**Screenshots**
output log: https://pastebin.com/zkEHWMS7

**Comment by modulesio** [comment]
Cool, this one sounds relatively easy. [We even have `HTMLBodyElement`](https://github.com/exokitxr/exokit/blob/master/src/Window.js#L112), it just wasn't on `window`.

I don't think https://developer.mozilla.org/en-US/docs/Web/API/HTMLBodyElement has much, if any necessary functionality to it.

**Comment by modulesio** [comment]
Worth trying this again, since https://github.com/exokitxr/exokit/pull/952 was merged.

**Comment by madjin** [comment]
Getting a new error `ReferenceError: HTMLDivElement is not defined`

output log: https://pastebin.com/wF7yGaG5

**Comment by modulesio** [comment]
With https://github.com/exokitxr/exokit/pull/953, we get further into widgets loading:

```
Error: #discord-widget element does not exist!
    at Object.<anonymous> (/assets/e5d3f5da2fab98ab650a.js:30:23854)
    at n (/assets/e5d3f5da2fab98ab650a.js:1:110)
    at /assets/e5d3f5da2fab98ab650a.js:1:910
    at /assets/e5d3f5da2fab98ab650a.js:1:920
    at Object._runJavascript (C:\Users\avaer\Documents\GitHub\exokit5\src\utils.js:71:15)
    at ownerDocument.defaultView.fetch.then.then.s (C:\Users\avaer\Documents\GitHub\exokit5\src\DOM.js:1675:17)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
TypeError: Cannot read property 'responseStart' of undefined
    at https://www.youtube.com/embed/PMAkpeyWGWA:3:2582
    at https://www.youtube.com/embed/PMAkpeyWGWA:3:3350
    at Object._runJavascript (C:\Users\avaer\Documents\GitHub\exokit5\src\utils.js:71:15)
    at Resource.ownerDocument.resources.addResource [as getCb] (C:\Users\avaer\Documents\GitHub\exokit5\src\DOM.js:1703:13)
    at Promise (C:\Users\avaer\Documents\GitHub\exokit5\src\core.js:46:12)
    at new Promise (<anonymous>)
    at Resource.get (C:\Users\avaer\Documents\GitHub\exokit5\src\core.js:45:12)
    at Resources.drain (C:\Users\avaer\Documents\GitHub\exokit5\src\core.js:124:16)
    at Promise (C:\Users\avaer\Documents\GitHub\exokit5\src\core.js:117:12)
    at new Promise (<anonymous>)
TypeError: Cannot read property 'closure_uid_173801530' of null
    at fh (/yts/jsbin/www-embed-player-vflpPiYjn/www-embed-player.js:534:113)
    at /yts/jsbin/www-embed-player-vflpPiYjn/www-embed-player.js:652:302
    at https://www.youtube.com/embed/PMAkpeyWGWA:12:29937
    at Object._runJavascript (C:\Users\avaer\Documents\GitHub\exokit5\src\utils.js:71:15)
```

**Comment by modulesio** [comment]
Better URL for testing: https://www.cryptovoxels.com/play?coords=NE@196E,90N

**Comment by modulesio** [comment]
More progress into the selector engine matching DOM elements -- possibly related to the new ones added.

```
TypeError: _.tagName.toUpperCase is not a function
    at eval (eval at selectorFn (C:\Users\avaer\Documents\GitHub\exokit5\node_modules\window-selector\selector.js:38:25), <anonymous>:3:61)
    at node.traverse.el (C:\Users\avaer\Documents\GitHub\exokit5\node_modules\window-selector\selector.js:91:11)
    at _recurse (C:\Users\avaer\Documents\GitHub\exokit5\src\DOM.js:1178:22)
    at _recurse (C:\Users\avaer\Documents\GitHub\exokit5\src\DOM.js:1184:28)
    at _recurse (C:\Users\avaer\Documents\GitHub\exokit5\src\DOM.js:1184:28)
    at _recurse (C:\Users\avaer\Documents\GitHub\exokit5\src\DOM.js:1184:28)
    at Document.traverse (C:\Users\avaer\Documents\GitHub\exokit5\src\DOM.js:1195:12)
    at Object.find (C:\Users\avaer\Documents\GitHub\exokit5\node_modules\window-selector\selector.js:90:10)
    at Document.getElementsByTagName (C:\Users\avaer\Documents\GitHub\exokit5\src\DOM.js:905:21)
    at Document.<anonymous> (https://www.cryptovoxels.com/client.js:39253:35)
```

**Comment by modulesio** [comment]
There's only one native error left:

```
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:775:18)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\avaer\Documents\GitHub\exokit5\src\native-bindings.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
```

I think we'll need to pull out the debugger for this.

**Comment by modulesio** [comment]
☝️ The above might be related to Web Workers.

**Comment by modulesio** [comment]
This loads clean now, but with no `<canvas>` window opening.

We'll probably need an unminified source to see where it's hanging the load.

**Comment by modulesio** [comment]
![Capture 27](https://user-images.githubusercontent.com/6926057/60092122-36709a00-9714-11e9-97cc-5db250d8c925.PNG)

Should be loading and walkable now.

**Comment by modulesio** [comment]
This has been working for a while, including in VR 😒.
