### ISSUE TITLE
Hmd Not Found error

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#968]
SteamVR can sometimes confuse Oculus Go as a HMD when there is no actual HMD. The solution is to unplug the Oculus Go.

**Comment by chrisplatorres** [comment]
an example:

```sh
$ node --experimental-worker . -h -t https://web.janusvr.com
THREE.WebGLRenderer 96dev
{ Error: Hmd Not Found (108)
    at Object.nativeBindings.nativeOpenVR.requestPresent (C:\Users\chris\github\exokit\src\index.js:629:77)
    at XRDevice.openVRDevice.onrequestpresent.layers [as onrequestpresent] (C:\Users\chris\github\exokit\src\Window.js:1387:60)
    at new XRWebGLLayer (C:\Users\chris\github\exokit\src\XR.js:356:22)
    at WebXRManager.setSession (three.js:21642:25)
    at session.requestAnimationFrame (file:///C:/Users/chris/github/exokit/examples/realitytabs.html?t=https%3A%2F%2Fweb.janusvr.com:2
722:23)
    at animationFrame.device.onrequestanimationframe.timestamp (C:\Users\chris\github\exokit\src\XR.js:143:9)
    at tickAnimationFrame (C:\Users\chris\github\exokit\src\Window.js:1318:15)
    at Immediate._renderLoop [as _onImmediate] (C:\Users\chris\github\exokit\src\index.js:2048:18)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23) code: 108 }
```

**Comment by modulesio** [comment]
Ideally we'd detect this case and in turn report no HMD's to the site. I don't yet know how OpenVR can be made to do that.

**Comment by chrisplatorres** [comment]
Got a similar error when having Oculus Quest plugged in.

VRInitError_Init_HmdNotFound "Hmd Not Found (108)"


![notfoundCapture](https://user-images.githubusercontent.com/29695350/58145915-95c12300-7c19-11e9-9b49-3b19c91e2fa1.PNG)
